neuronbot:
  robot_description: ['neuronbot_description', 'robots', 'neuronbot.urdf.xacro']
  rqt_robot_steering: true
  robot_name_prefix: 'ironman'
  enable_odom: true
  enable_amcl: true # If true, enable_odom must be true
  scan_base_name: 'front_scan' # Without namespace, used for amcl
  pose:
    - [0.5, 0.5, 0] # x,y,yaw

d435_n:
  robot_description: ['d435_description', 'robots', 'camera.urdf.xacro']
  rqt_robot_steering: false
  robot_name_prefix: 'camera_north'
  enable_odom: false
  enable_amcl: false # If true, enable_odom must be true
  pose:
    - [-0.84, 1.4, 1.8, 0, 1.57, 0] # x,y,z,r,p,y

d435_s:
  robot_description: ['d435_description', 'robots', 'camera.urdf.xacro']
  rqt_robot_steering: false
  robot_name_prefix: 'camera_south'
  enable_odom: false
  enable_amcl: false # If true, enable_odom must be true
  pose:
    - [-0.77, -0.5, 1.8, 0, 1.57, 0] # x,y,z,r,p,y
